### ISSUE TITLE
Error when Game is Loading

### ISSUE THREAD

**Issue by stats** [Kinniken/NoxImperii#3]
I had an error when loading the game that prevented me from playing. This error occurs when **Loading the Universe** is the active text on the loading bar.

The version is 0.5.1 which was downloaded off the nox imperii website direct windows download link.

My systems specs are Windows 7 Pro 64 bit. i7 processor with 8GB of RAM.

If you need any other information about this please let me know.

![noxerror](https://cloud.githubusercontent.com/assets/786312/20482261/bbacd2be-afb9-11e6-9940-cf28daf03d63.png)

**Comment by Kinniken** [comment]
Hi,

Could you check the log files? They should be in C:\Users\<your user name>\AppData\Roaming\noximperii\logs .

Thanks

K.

**Comment by stats** [comment]
The log file gave the problem away. NOX needed to be run with the graphics card, which it was not by default.

```
AL lib: (EE) GetSymbol: Failed to load fluid_synth_set_channel_type
Warning: [al_checkHandleError] OpenAL error [al_enableEFX]: an invalid value was passed to an OpenAL function
Warning: [gl_checkHandleError] OpenGL error [gl_loadSurface:376]: GL out of memory
ERROR npng.c:358 [npng_readSurface]: Out of Memory
AL lib: (EE) alc_cleanup: 1 device not closed
```

I changed the graphics card settings for the application and it loaded. Thank you!

**Comment by Kinniken** [comment]
Great, thanks for the info. I'll see if I can handle this error better. What computer are you playing on? A laptop with both integrated graphics and a separated graphic card?

**Comment by stats** [comment]
This is on a laptop, I must select where to enable to graphics processor or not on certain applications.

**Comment by Kinniken** [comment]
Thanks, that's what I thought. Have fun with the game!
